on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  code-scan-ingestor:
    uses: ./python-code-scan.yml@main
    with:
      working-directory: ./ingestor

  code-scan-api:
    uses: ./python-code-scan.yml@main
    with:
      working-directory: ./api

